name: null
favicon: null
layout_spectrum: 0.24262
typography_spectrum: 0.37542
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7d7cf'
    - '#010101'
    - '#766a55'
    - '#bfa096'
    - '#da2820'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: null
    url: null
