name: null
favicon: null
layout_spectrum: 0.24262
typography_spectrum: 0.37542
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#ffffff'
    - '#948973'
    - '#676050'
    - '#b6a790'
  brandStrength: 0
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0.75
purpose:
  - name: follow
    item: null
    url: null
