typography_spectrum: 0.37542
color:
  brandColors:
    - '#030303'
    - '#ffffff'
    - '#948973'
    - '#676050'
    - '#b6a790'
  brandStrength: 0
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24262
analytics:
  google: null
  facebook: null
  twitter: null
name: Spencer Connaughton
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: The Blog of Spencer Connaughton
purpose: []
